# Create a new project: docker-compose run app django-admin.py startproject name_of_project
version: '3'

services:

  postgres:
    restart: always
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: db_user
      POSTGRES_DB: db_database
    build:
      context: .
      dockerfile: ./Dockerfile_Postgres
    image: django:postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  app:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile_Python
    image: django:app    
    links:
      - postgres:postgres
    command: python ./manage.py runserver 0.0.0.0:8000
    working_dir: /code/play_project
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres